// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Opus127.Dengue.Api.Data;

#nullable disable

namespace Opus127.Dengue.Api.Migrations
{
    [DbContext(typeof(DengueDbContext))]
    partial class DengueDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Opus127.Dengue.Api.Entities.DengueWeeklyAlert", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AlertLevel")
                        .HasColumnType("int");

                    b.Property<int>("EpidemiologicalWeek")
                        .HasColumnType("int");

                    b.Property<int>("EpidemiologicalYear")
                        .HasColumnType("int");

                    b.Property<decimal>("EstimatedCases")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Geocode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NotifiedCases")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("SyncedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("EpidemiologicalYear", "EpidemiologicalWeek")
                        .IsUnique();

                    b.ToTable("DengueWeeklyAlerts", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
